image: node:13.7

stages:
  - test
  - run:primary
  - run:secondary
  - deploy

before_script:
  - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  - npm i -g lerna
  - lerna bootstrap

tests:
  type: test
  script:
    - npm ci
    - npm run test

exec:lint:
  type: run:primary
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js lint
  except:
    - master
    - production

exec:build:
  type: run:primary
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js build
  except:
    - master
    - production

exec:deploy:
  type: run:primary
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js deploy
  except:
    - master
    - production

.sync:
  before_script:
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - apt-get update -y
    - 'which ssh-agent || ( apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_AND_GITLAB_SYNC_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "ci@halfhelix.com"
    - git config --global user.name "Half Helix"
    - npm i -g lerna
    - lerna bootstrap

exec:sync:a:
  extends: .sync
  type: run:secondary
  script:
    - cd ./packages/theme/basic-test
    - npm i
    - node ../../cli/cli.js build --sync-with-repo
  except:
    - master
    - production

exec:sync:b:
  extends: .sync
  type: run:secondary
  script:
    - cd ./packages/theme/basic-built-theme-test
    - npm i
    - node ../../cli/cli.js sync-back-to-source-repo
  except:
    - master
    - production

.deploy:
  type: deploy
  before_script:
    - apt-get update -y
    - 'which ssh-agent || ( apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_DEPLOY_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo //registry.npmjs.org/:_authToken=$NPM_PUBLISH_KEY >> .npmrc
    - npm whoami
    - git config --global user.email $GIT_EMAIL
    - git config --global user.name $GIT_NAME
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - git remote remove origin
    - git remote add origin git@gitlab.com:halfhelix/kit.git
    - git fetch origin
    - npm i -g lerna
    - lerna bootstrap
  when: manual
  only:
    - master
    - production

deploy:major:
  extends: .deploy
  script:
    - lerna publish major --no-verify-access --yes

deploy:minor:
  extends: .deploy
  script:
    - lerna publish minor --no-verify-access --yes

deploy:patch:
  extends: .deploy
  script:
    - lerna publish patch --no-verify-access --yes

deploy:prerelease:
  extends: .deploy
  script:
    - lerna publish prerelease --no-verify-access --yes
