name: execute
on:
  push:
    branches-ignore:
      - 'master'
      - 'production'
jobs:
  exec-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13.7'
      - run: npm i -g lerna
      - run: lerna bootstrap
      - name: Run linting command
        working-directory: ./packages/theme/basic-test
        run: node ./packages/cli/cli.js lint
  # exec-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '13.7'
  #     - run: npm i -g lerna
  #     - run: lerna bootstrap
  #     - run: cd ./packages/theme/basic-test
  #     - run: npm i
  #     - run: node ../../cli/cli.js build
  # exec-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '13.7'
  #     - run: npm i -g lerna
  #     - run: lerna bootstrap
  #     - run: cd ./packages/theme/basic-test
  #     - run: npm i
  #     - run: node ../../cli/cli.js deploy