name: test
on:
  push:
    branches-ignore:
      - 'feature/github-actions'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13.7'
      - run: npm i -g lerna
      - run: lerna bootstrap
      - run: npm ci
      - run: npm run test